### PR TITLE
fix: replace 'uname -a' with 'uname -srm' for OS/Arch detection

### LINKED ISSUE #561: [Bug] Weak OS detection
## What went wrong?

My linux computer's name (or `hostname`) includes `mac`, and `https://webi.sh/api/` thinks it's macOS.

User-Agent:

```
curl Linux river-virtual-machine 5.19.0-31-generic #32-Ubuntu SMP PREEMPT_DYNAMIC Fri Jan 20 15:20:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux"
                         👆 Here is the “mac”.
    (“river-virtual-machine” is my computer's name)
```

You can reproduce it on any platform: manually `curl -H …`, then `-machine` receives macOS, and `-mahine` receives `linux`.

> **Note**: The following is a detective story that might be off-topic. So skip if you want.

## What were you trying to install (or what else went wrong)?

I tried to install `lsd` first, but `pathman` seemed to be broken (`Exec format error`).

_Remark_: I never install `pathman` before — it was required by the script. However, I believe this won't get fixed even after #505 is completed.

Then I [uninstalled everything that installed with webi](https://webinstall.dev/faq/#uninstall-webi), and [`curl -sS https://webi.sh/pathman | sh`](https://webinstall.dev/pathman/). This time `pathman` was installed, but still broken:

```bash
$ pathman --help
… cannot execute binary file: exec format error
```

I modify those scripts and find what webi really downloads is `pathman-v0.5.2-macos-amd64.tar.gz`.

```bash
$ curl https://webi.sh/api/installers/pathman@stable.sh?formats=tar,exe,zip,xz,git,dmg -sS | rg -e 'WEBI_RELEASES=.+?os=[^&]+&'
WEBI_RELEASES='https://webi.sh/…?os=linux… ✔️

$ uname -a
Linux river-virtual-machine 5.19.0-31-generic #32-Ubuntu SMP PREEMPT_DYNAMIC Fri Jan 20 15:20:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

$ curl https://webi.sh/api/installers/pathman@stable.sh?formats=tar,exe,zip,xz,git,dmg -sS -H "User-Agent: curl $(uname -a)" | rg -e 'WEBI_RELEASES=.+?os=[^&]+&'
WEBI_RELEASES='https://webi.sh/…?os=macos… ❌
```

## What exactly did you do?

`curl -sS https://webi.sh/pathman | sh` for a fresh install.

## Which OS did you try on?

- [ ] Mac
- [x] Windows (Host)
- [x] Linux (Guest)

## What type of computer (i.e. laptop, desktop, Raspberry Pi)?

- [x] Laptop or Desktop (amd64 / x86-64)
- [ ] Raspberry Pi (ARM-64)
- [ ] Other (please specify, if you know)

### PR DESCRIPTION
**Pull request by coolaj86**
fixes #561, and possibly an old issue with 32-bit vs 64-bit OS on 64-bit Raspberry Pi - we hope :)

## In Theory

| Flag | Meaning | Example |
| ----- | --------------- | -------------------- |
| `-s` | `operating system implementation` | `Darwin` |
| `-r` | `operating system release level` | `22.2.0` <br> (i.e. of Darwin) |
| `-v` | `operating system release version` | `#89-Ubuntu SMP PREEMPT Mon Dec 5 08:38:35 UTC 2022` |
| `-m` | `machine platform` | `arm64` |
| `-p` | *non-standard* <br> `machine processor architecture` | `arm` |

## In Practice

```sh
uname -srm
```

```text
# Mac
Darwin 22.2.0 arm64

# Linux
Linux 5.15.0-50-generic x86_64

# Raspberry Pi (64-bit OS on aarch64)
Linux 5.4.0-1078-raspi aarch64

# Raspberry Pi (32-bit OS on aarch64)
Linux 5.15.32-v7l+ armv7l
```

```sh
uname -v
```

```text
# Mac
Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000

# Linux
#89-Ubuntu SMP PREEMPT Mon Dec 5 08:38:35 UTC 2022

# Raspberry Pi (64-bit OS on aarch64)
#89-Ubuntu SMP PREEMPT Mon Dec 5 08:38:35 UTC 2022

# Raspberry Pi (32-bit OS on aarch64)
#1538 SMP Thu Mar 31 19:39:41 BST 2022 
```

```sh
uname -srmp
```

```text
# Mac
Darwin 22.2.0 arm64 arm

# Linux
Linux 5.15.0-50-generic x86_64 x86_64

# Raspberry Pi (64-bit OS on aarch64)
Linux 5.4.0-1078-raspi aarch64 aarch64

# Raspberry Pi (32-bit OS on aarch64)
Linux 5.15.32-v7l+ armv7l unknown
```

## Caveat: We need the LIES!

If we _really_ wanted to know the _truth_ on a raspberry pi, we could use `getconf LONG_BIT`.

```sh
getconf LONG_BIT
```

```text
64
```

However, what actually matters is not the _real_ CPU, but the CPU that the OS was built for.

### CODE REVIEW

File: _webi/bootstrap.sh [hunk 1]
```diff
@@ -15,7 +15,11 @@ __install_webi() {
     export WEBI_HOST
 
     echo ""
+<<<<<<< HEAD
```
Comment (y0rune) [inline _webi/bootstrap.sh:18]: As far I see still here is the junk staff from diff :D

**Review by y0rune — CHANGES_REQUESTED** [review]

**Review by y0rune — APPROVED** [review]
LGTM!

**Comment by y0rune** [comment]
Tested on RPI:
```
raspberry-vpn ~ master $ curl -sS https://beta.webi.sh/webi | sh

Thanks for using webi to install 'webi@stable' on 'Linux/5.15.32-v7l+/armv7l'.
Have a problem? Experience a bug? Please let us know:
        https://github.com/webinstall/webi-installers/issues

Lovin' it? Say thanks with a Star on GitHub:
        https://github.com/webinstall/webi-installers


'webi' installed to ~/.local/bin/webi

Usage:
    webi <package-name>[@version] ...

Example:
    webi node@lts prettier vim-essentials

raspberry-vpn ~ master $ webi shfmt

Thanks for using webi to install 'shfmt' on 'Linux/armv7l'.
Have a problem? Experience a bug? Please let us know:
        https://github.com/webinstall/webi-installers/issues

Lovin' it? Say thanks with a Star on GitHub:
        https://github.com/webinstall/webi-installers

Downloading shfmt from
https://github.com/mvdan/sh/releases/download/v3.6.0/shfmt_v3.6.0_linux_arm

Saved as /root/Downloads/webi/shfmt/3.6.0/shfmt_v3.6.0_linux_arm
Moving /root/Downloads/webi/shfmt/3.6.0/shfmt_v3.6.0_linux_arm
Installing to /root/.local/opt/shfmt-v3.6.0/bin/shfmt
Installed 'shfmt v3.6.0' as /root/.local/bin/shfmt

raspberry-vpn ~ master $ shfmt --version
v3.6.0
```
